# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='group_name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupTracker.GroupClass'),
        ),
    ]
