# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupTracker', '0003_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_class',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupClass',
        ),
    ]
