# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupTracker', '0005_auto_20160911_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinfo',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='groupinfo',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
